import {
  Activity,
  ArrowRight,
  AtSign,
  Award,
  BadgeCheck,
  Banknote,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Brain,
  Briefcase,
  Building,
  Calendar,
  CalendarCheck,
  Camera,
  Car,
  ChartBar,
  ChartLine,
  Check,
  CircleCheck,
  CircleHelp,
  ClipboardCheck,
  Clock,
  Cloud,
  Code,
  Coffee,
  Coins,
  Cpu,
  CreditCard,
  Crown,
  Database,
  FileText,
  Flame,
  Folder,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  Home,
  Image as ImageIcon,
  Infinity as InfinityIcon,
  Info,
  Key,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Link as LinkIcon,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Newspaper,
  Palette,
  PartyPopper,
  Pencil,
  Plane,
  Play,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  TrendingUp,
  Trophy,
  User,
  UserCheck,
  UserPlus,
  Users,
  Video,
  Wallet,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { LandingIcon } from "@/lib/landing-schema";

/** Static map of the site-page icon allowlist – single source for renderer and pickers. */
export const LANDING_ICON_MAP: Record<LandingIcon, LucideIcon> = {
  sparkles: Sparkles,
  users: Users,
  "message-circle": MessageCircle,
  calendar: Calendar,
  "book-open": BookOpen,
  workflow: Workflow,
  shield: Shield,
  zap: Zap,
  heart: Heart,
  globe: Globe,
  lightbulb: Lightbulb,
  rocket: Rocket,
  target: Target,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  brain: Brain,
  user: User,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  smile: Smile,
  "party-popper": PartyPopper,
  "thumbs-up": ThumbsUp,
  star: Star,
  award: Award,
  trophy: Trophy,
  crown: Crown,
  gem: Gem,
  gift: Gift,
  check: Check,
  "circle-check": CircleCheck,
  "badge-check": BadgeCheck,
  "shield-check": ShieldCheck,
  info: Info,
  "circle-help": CircleHelp,
  mail: Mail,
  send: Send,
  bell: Bell,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  "at-sign": AtSign,
  "share-2": Share2,
  link: LinkIcon,
  briefcase: Briefcase,
  building: Building,
  store: Store,
  banknote: Banknote,
  "credit-card": CreditCard,
  wallet: Wallet,
  coins: Coins,
  "chart-line": ChartLine,
  "chart-bar": ChartBar,
  "trending-up": TrendingUp,
  activity: Activity,
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  cpu: Cpu,
  database: Database,
  server: Server,
  cloud: Cloud,
  code: Code,
  terminal: Terminal,
  bot: Bot,
  settings: Settings,
  wrench: Wrench,
  "file-text": FileText,
  folder: Folder,
  "clipboard-check": ClipboardCheck,
  pencil: Pencil,
  book: Book,
  library: Library,
  newspaper: Newspaper,
  bookmark: Bookmark,
  search: Search,
  camera: Camera,
  image: ImageIcon,
  video: Video,
  mic: Mic,
  headphones: Headphones,
  play: Play,
  home: Home,
  map: MapIcon,
  "map-pin": MapPin,
  plane: Plane,
  car: Car,
  clock: Clock,
  "calendar-check": CalendarCheck,
  sun: Sun,
  moon: Moon,
  leaf: Leaf,
  mountain: Mountain,
  flame: Flame,
  coffee: Coffee,
  lock: Lock,
  key: Key,
  tag: Tag,
  palette: Palette,
  "arrow-right": ArrowRight,
  "refresh-cw": RefreshCw,
  infinity: InfinityIcon,
};
